### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Zazo032** [ShekarMudaliyar/social_share#1]
Issue to track Android plugin support. We're really interested in using this plugin but being iOS-only is a blocker for us.

**Comment by ShekarMudaliyar** [comment]
Working on it lately, happy to announce its almost done for android just some fixes and tests are left. Follow me on [twitter](https://twitter.com/0_B1NARY) to know when this plugin gets updated

**Comment by ShekarMudaliyar** [comment]
Support for android is live now you can check it out
