### ISSUE TITLE
iOS bug rotating portrait image to landscape in Instagram story

### ISSUE THREAD

**Issue by blaueeiner** [ShekarMudaliyar/social_share#10]
Hi I am trying to share an image to instagram story. The image is definitely in portrait mode but for some reason inside Instagram the image is rotated by 90 degrees. If it was a landscape image.
It is important to know that if I take a landscape image it is shared correctly. This one is not rotated or something else.

**Comment by ShekarMudaliyar** [comment]
maybe there's something with the image coz sometimes Instagram rotates image according to the dimension
