### ISSUE TITLE
Sharing to Instagram Stories image size

### ISSUE THREAD

**Issue by ScottishRoss** [ShekarMudaliyar/social_share#101]
I have an image that's the preferred size of an Instagram Story (1080 by 1920), but when I share with Instagram it doesn't take up the whole image.

https://drive.google.com/file/d/1vwM2wQ7vjypVimoPovAvNyx72VAO3rlB/view?usp=sharing

Is there any way to make the image take up the whole Story?

**Comment by bwrelawan** [comment]
@ScottishRoss you must add other plugin, that is Screenshot. This is code for you if you want customize your image:
`var container = Container(
                                padding: const EdgeInsets.all(30.0),
                                decoration: BoxDecoration(
                                  color: AppColors.bluemain,
                                ),
                                child: Container(
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.all(Radius.circular(10)),
                                    color: Colors.white,
                                  ),
                                  height: 360,
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    children: [
                                      Padding(
                                        padding: const EdgeInsets.all(8.0),
                                        child: Text(
                                          'Pabrik di Inggris Bakal Ditutup, Manajemen: Tak Berdampak ke Bisnis Nestle di Indonesia',
                                          style: TextStyle(color: Colors.black),
                                        ),
                                      ),
                                      Card(
                                        clipBehavior: Clip.antiAliasWithSaveLayer,
                                        child: Image.network(
                                          'https://img.inews.co.id/media/800/files/inews_new/2022/02/15/rusia_ukraina_news_recti__inews.jpg',
                                          fit: BoxFit.fill,
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(10.0),
                                        ),
                                        elevation: 5,
                                        margin: EdgeInsets.all(10),
                                      ),
                                      Padding(
                                        padding: const EdgeInsets.all(8.0),
                                        child: SvgPicture.asset(
                                          AppAssets.buddykulogo,
                                          height: 20,
                                        ),
                                      ),
                                    ],
                                  ),
                                ));
                            screenshotController.captureFromWidget((container), delay: Duration(seconds: 1)).then((capturedImage) async {
                              //ShowCapturedWidget(context, capturedImage);
                              if (capturedImage != null) {
                                final directory = await getApplicationDocumentsDirectory();
                                final imagePath = await File('${directory.path}/image.png').create();
                                await imagePath.writeAsBytes(capturedImage);

                                /// Share Plugin
                                SocialShare.shareInstagramStory(
                                  imagePath.path,
                                  backgroundTopColor: "#ffffff",
                                  backgroundBottomColor: "#000000",
                                  attributionURL: "https://deep-link-url",
                                );
                              }
                            });`

**Comment by bwrelawan** [comment]
@ScottishRoss  you must add other plugin, that is Screenshot. This is code for you if you want customize your image:
`var container = Container(
                                padding: const EdgeInsets.all(30.0),
                                decoration: BoxDecoration(
                                  color: AppColors.bluemain,
                                ),
                                child: Container(
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.all(Radius.circular(10)),
                                    color: Colors.white,
                                  ),
                                  height: 360,
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    children: [
                                      Padding(
                                        padding: const EdgeInsets.all(8.0),
                                        child: Text(
                                          'Pabrik di Inggris Bakal Ditutup, Manajemen: Tak Berdampak ke Bisnis Nestle di Indonesia',
                                          style: TextStyle(color: Colors.black),
                                        ),
                                      ),
                                      Card(
                                        clipBehavior: Clip.antiAliasWithSaveLayer,
                                        child: Image.network(
                                          'https://img.inews.co.id/media/800/files/inews_new/2022/02/15/rusia_ukraina_news_recti__inews.jpg',
                                          fit: BoxFit.fill,
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(10.0),
                                        ),
                                        elevation: 5,
                                        margin: EdgeInsets.all(10),
                                      ),
                                      Padding(
                                        padding: const EdgeInsets.all(8.0),
                                        child: SvgPicture.asset(
                                          AppAssets.buddykulogo,
                                          height: 20,
                                        ),
                                      ),
                                    ],
                                  ),
                                ));
                            screenshotController.captureFromWidget((container), delay: Duration(seconds: 1)).then((capturedImage) async {
                              //ShowCapturedWidget(context, capturedImage);
                              if (capturedImage != null) {
                                final directory = await getApplicationDocumentsDirectory();
                                final imagePath = await File('${directory.path}/image.png').create();
                                await imagePath.writeAsBytes(capturedImage);

                                /// Share Plugin
                                SocialShare.shareInstagramStory(
                                  imagePath.path,
                                  backgroundTopColor: "#ffffff",
                                  backgroundBottomColor: "#000000",
                                  attributionURL: "https://deep-link-url",
                                );
                                //await Share.shareFiles([imagePath.path]);
                              }
                            });`

**Comment by ScottishRoss** [comment]
@bwrelawan thanks for the suggestion, but I have a way of capturing the image required. The issue is that when sharing that image with Instagram, it doesn't take up the whole story image (as per the screenshot I shared). The image is sized correctly for Instagram story dimensions too.

**Comment by bwrelawan** [comment]
yess @ScottishRoss , before you share file.path from your image, convert it as a widget (screenshot) then convert it to image again, so you can resize the image whatever you want.

**Comment by ScottishRoss** [comment]
I updated this and it seems to work better:
`final ui.Image image = await boundary.toImage(pixelRatio: 10);`

**Comment by ihorkozar** [comment]
@ScottishRoss Please tell me how you solved this problem.

**Comment by kamranbekirovyz** [comment]
@ScottishRoss I'm interested too 👀
