### ISSUE TITLE
Android (AVD) doesn't work for sharing instagram and facebook.

### ISSUE THREAD

**Issue by sonny-SW-Developer** [ShekarMudaliyar/social_share#147]
Did someone resolve this issue? It doesn't work in Android but well in IOS.
Why Android have a issue? 
When I called checkInstalledAppsForShare(), my phone already installed instagram and facebook, but the result is false. 
Also, when I used shareInstagramStory, It doesn't work.. 
Please anyone help.
Thanks.

**Comment by CarlosMedina10** [comment]
Can you solve this?
