### ISSUE TITLE
[android] Can't have multiple FileProviders

### ISSUE THREAD

**Issue by Zazo032** [ShekarMudaliyar/social_share#2]
When using other plugins that require a `FileProvider`, you can't compile the app as only one of the providers is valid.  The fix is to change `.provider` to `.fileProvider` in the following lines:

https://github.com/ShekarMudaliyar/social_share/blob/master/android/src/main/kotlin/com/shekarmudaliyar/social_share/SocialSharePlugin.kt#L43
https://github.com/ShekarMudaliyar/social_share/blob/master/android/src/main/kotlin/com/shekarmudaliyar/social_share/SocialSharePlugin.kt#L52
https://github.com/ShekarMudaliyar/social_share/blob/master/android/src/main/kotlin/com/shekarmudaliyar/social_share/SocialSharePlugin.kt#L79
https://github.com/ShekarMudaliyar/social_share/blob/master/android/src/main/kotlin/com/shekarmudaliyar/social_share/SocialSharePlugin.kt#L110

So it doesn't collide with other plugins (like `open_file`).

**Comment by ShekarMudaliyar** [comment]
Changed the FileProvider dir. Check out the new update 2.0.1
