### ISSUE TITLE
Share images to WhatsApp

### ISSUE THREAD

**Issue by mayurdhurpate** [ShekarMudaliyar/social_share#21]
Currently, WhatsApp supports sharing Image along with text via [Intent](https://stackoverflow.com/questions/23077338/share-image-and-text-through-whatsapp-or-facebook), for Android (not sure of iOS). Would be great if we could add this option to the current WhatsApp sharing options.

**Comment by ShekarMudaliyar** [comment]
Thanks for the suggestion wont be able for ios but can try for android

**Comment by armandojimenez** [comment]
Can this be done?
