### ISSUE TITLE
error sharing Facebook & Instagram

### ISSUE THREAD

**Issue by DanielCardona** [ShekarMudaliyar/social_share#3]
Hi and thanks for your work ;-) !!
I have an error when trying to share on Instagram or Facebook, only tried on Android, the error on console is:

D/        (20476): company.appname.MainActivity@4e82c7c
I/flutter (20476): error

**Comment by ShekarMudaliyar** [comment]
did you copied the code into manifest file and also created the filepaths.xml ?

**Comment by DanielCardona** [comment]
Now it works ;-), I didn't touch anything, maybe I should do a flutter clean yesterday, anyway Thank You very much @ShekarMudaliyar !!
