### ISSUE TITLE
social_share/SocialSharePlugin.kt: (131, 11): Val cannot be reassigned

### ISSUE THREAD

**Issue by offline-first** [ShekarMudaliyar/social_share#35]
Android with compile sdk version >= 29 bug, Val cannot be reassigned:
`clipboard.primaryClip = clip ` 

hotfix with warning: 
`clipboard.setPrimaryClip(clip) `

**Comment by imSaharukh** [comment]
facing the same problem

**Comment by Purus** [comment]
Same problem when compiling the flutter app

```
H:\flutter\.pub-cache\hosted\pub.dartlang.org\social_share-2.0.5\android\src\main\kotlin\com\shekarmudaliyar\social_share\SocialSharePlugin.kt: (131, 11): Val cannot be reassigned

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':social_share:compileDebugKotlin'.
```

**Comment by CalHoll** [comment]
Same here, I didn't create the app with Kotlin and I need it to be Java for another plugin. were either of you able to make it work?

**Comment by syeds-git** [comment]
anyone got this fixed?

**Comment by ternes3** [comment]
The hotfix is already implemented in the repository, so this can be solved temporarily:

```
  social_share:
    git:
      url: git://github.com/ShekarMudaliyar/social_share.git
```

**Comment by ChiragRathod090** [comment]
You can replace line number : 128,
clipboard.primaryClip = clip with below line
clipboard.setPrimaryClip(clip)

**Comment by ShekarMudaliyar** [comment]
This issue is fixed you'll can directly update package from pubspec
