### ISSUE TITLE
How can I share image to Twitter? 

### ISSUE THREAD

**Issue by kakudenbuzo** [ShekarMudaliyar/social_share#39]

**Comment by nafidurmus** [comment]
I'm looking for a way to do this too. Did you find a solution?

**Comment by kakudenbuzo** [comment]
I'm using esys_flutter_share instead, but it's not exactly what I want...

**Comment by ShekarMudaliyar** [comment]
twitter does not allow to share images. You can share it using more options from this package but not directly
