### ISSUE TITLE
Migrate to null safety?

### ISSUE THREAD

**Issue by yusriltakeuchi** [ShekarMudaliyar/social_share#48]
Did you have a plan to migrate this to null safety?

**Comment by ShekarMudaliyar** [comment]
Will be doing that soon

**Comment by yusriltakeuchi** [comment]
Thankyou

**Comment by FetFrumos** [comment]
Please, it is important

**Comment by ShekarMudaliyar** [comment]
Ive pushed new update and migrated to null safety, check and let me know
