### ISSUE TITLE
Share to Instagram Stories does not work

### ISSUE THREAD

**Issue by guilhermeagostinelli** [ShekarMudaliyar/social_share#5]
Instagram Stories is opened with a black screen (no image).

It happens when loading a network image:

```dart
var response = await get("https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg");
Directory tempDir = await getTemporaryDirectory();
File file = File('${tempDir.path}/test.jpg');
File createdFile = await file.create(recursive: true);
if (await createdFile.exists())
    file.writeAsBytesSync(response.bodyBytes);
SocialShare.shareInstagramStory(file.path, "#ffffff", "#000000", "https://deep-link-url");
```

And also when selecting an image through [ImagePicker](https://pub.dev/packages/image_picker):

```dart
File file = await ImagePicker.pickImage(source: ImageSource.gallery);
SocialShare.shareInstagramStory(file.path, "#ffffff", "#000000", "https://deep-link-url");
```
![Instagram Stories Problem](https://user-images.githubusercontent.com/34043575/73882890-a8c86180-4841-11ea-8fd0-7ad1f5b893f1.png)

**Comment by ShekarMudaliyar** [comment]
is this android or ios?

**Comment by ShekarMudaliyar** [comment]
It worked for me with network image
```
 var response = await get(
                        "https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg");
                    Directory tempDir = await getTemporaryDirectory();
                    File file = File('${tempDir.path}/test.jpg');
                    File createdFile = await file.create(recursive: true);
                    if (await createdFile.exists())
                      file.writeAsBytesSync(response.bodyBytes);
                    SocialShare.shareInstagramStory(file.path, "#ffffff",
                            "#000000", "https://deep-link-url")
                        .then((data) {
                      print(data);
                    });
```
![IMG_0013](https://user-images.githubusercontent.com/26038316/73955190-f5d33300-4928-11ea-91a3-328a964c8fc5.png)

same with ImagePicker

```
File file = await ImagePicker.pickImage(
                        source: ImageSource.gallery);
                    SocialShare.shareInstagramStory(file.path, "#ffffff",
                            "#000000", "https://deep-link-url")
                        .then((data) {
                      print(data);
                    });
```
![Send To](https://user-images.githubusercontent.com/26038316/73955209-fc61aa80-4928-11ea-8ad2-d3250669becf.png)

just check if you have configured the app properly

**Comment by guilhermeagostinelli** [comment]
Hmm, that's weird, the problem persists for me. The `shareInstagramStory` function returns "success" and Instagram Stories is opened with a black image. I'm using an android device.

When running on an android emulator, the function returns "error" but no exception is thrown.

**Comment by ShekarMudaliyar** [comment]
can you check in verbose mode for instagram too?
Coz there might be some error while parsing image to instagram

**Comment by guilhermeagostinelli** [comment]
Hey guys,

I don't know if it is related to the newest Flutter version, but I've just checked it out again and now the code won't even compile. I'm getting the following error:

```
/home/guilherme/Desktop/mobile_app/android/app/src/debug/AndroidManifest.xml Error:
	Attribute provider#androidx.core.content.FileProvider@authorities value=(com.positiv.positiv_mobile_app.com.shekarmudaliyar.social_share) from (unknown)
	is also present at [:open_file] AndroidManifest.xml:14:13-64 value=(com.positiv.positiv_mobile_app.fileProvider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute provider#androidx.core.content.FileProvider@authorities value=(com.positiv.positiv_mobile_app.com.shekarmudaliyar.social_share) from (unknown)
  	is also present at [:open_file] AndroidManifest.xml:14:13-64 value=(com.positiv.positiv_mobile_app.fileProvider).
  	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

**Comment by guilhermeagostinelli** [comment]
Just managed to solve it by adding `xmlns:tools="http://schemas.android.com/tools"` to the `<manifest>` element and `tools:replace="android:authorities"` to `<provider>` element at AndroidManifest.xml to override.

@ShekarMudaliyar I can submit a PR for this if you agree.

**Comment by guilhermeagostinelli** [comment]
Now, when testing to the see if the black screen problem persists, it still doesn't work. Now, Instagram won't even open and the function returns "error". I'm using the same device as before, running on Android 6.0.1.

However, when testing on another device (Android 7.0), it works perfectly. Please consider adding an incompatibility notice in the project's README file.

**Comment by ShekarMudaliyar** [comment]
Go Ahead do the required changes Submit a PR

**Comment by abdulhafidz** [comment]
this is because the file is jpg. workaround for me is convert it to png before sharing.
