### ISSUE TITLE
Share Facebook Feed ?

### ISSUE THREAD

**Issue by yusriltakeuchi** [ShekarMudaliyar/social_share#78]
Can we share to facebook feed? not facebook story. I need this feature to share link in facebook feed.

**Comment by jkronlachner** [comment]
you can use the flutter default share pub: 
https://pub.dev/packages/share_plus

**Comment by yusriltakeuchi** [comment]
> you can use the flutter default share pub:
> https://pub.dev/packages/share_plus

is that support for facebook share? i think it just use default share android.

**Comment by jkronlachner** [comment]
ah i think i see. you *only* want to share to fb.

**Comment by yusriltakeuchi** [comment]
> ah i think i see. you _only_ want to share to fb.

Yes, i try with another package to share Facebook, but it's crash on android. I send an issue but nothing answer until now
