### ISSUE TITLE
The plugin `social_share` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by HenryDeveloper** [ShekarMudaliyar/social_share#85]
**Flutter Doctor**
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on Ubuntu 18.04.5 LTS 5.4.72-microsoft-standard-WSL2, locale en_US.UTF-8)
    • Flutter version 2.5.0-7.0.pre.83 at /home/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (3 weeks ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Platform android-30, build-tools 29.0.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
    • All Android licenses accepted.

**Issue**
Hi social share team, when run the command _flutter pub get_ a warning message is showing:
![image](https://user-images.githubusercontent.com/11890226/132027653-7a86e8c8-d5f2-4fed-bbaa-e1ef1ae9b6f1.png)

I would like to know, if in the near future this will be updated to the version that is recommended by the android framework? This package seems excellent to me and I hope you continue to support :) 

Thank you very much in advance.

Best Regards.

**Comment by ajosecueto** [comment]
Same issue...

**Comment by mikaelim-id** [comment]
I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.

`  place_picker:
    git: https://github.com/mikaelim-id/locationpicker`

**Comment by HenryDeveloper** [comment]
Thank so much @mikaelim-id, 

I will take a look to this version and I'm waiting for the stable version in master 😄

**Comment by zakblacki** [comment]
> I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> 
> ` place_picker: git: https://github.com/mikaelim-id/locationpicker`

wrong format Mapping values are not allowed here 
what should we put in pubspec ?

**Comment by mikaelim-id** [comment]
> > I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> > ` place_picker: git: https://github.com/mikaelim-id/locationpicker`
> 
> wrong format Mapping values are not allowed here
> what should we put in pubspec ?

you should put the package in pubspec like this
`place_picker: `
`  git: https://github.com/mikaelim-id/locationpicker`

**Comment by MDSADABWASIM** [comment]
> I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> 
> ` place_picker: git: https://github.com/mikaelim-id/locationpicker`

This is location picker plugin, can you give exact url that we need to add @mikaelim-id

**Comment by mikaelim-id** [comment]
> > I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> > ` place_picker: git: https://github.com/mikaelim-id/locationpicker`
> 
> This is location picker plugin, can you give exact url that we need to add @mikaelim-id

Sorry. The url should be this
`social_share: git: https://github.com/mikaelim-id/social_share`

**Comment by MDSADABWASIM** [comment]
> > > I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> > > ` place_picker: git: https://github.com/mikaelim-id/locationpicker`
> > 
> > 
> > This is location picker plugin, can you give exact url that we need to add @mikaelim-id
> 
> Sorry. The url should be this
> `social_share: git: https://github.com/mikaelim-id/social_share`

Thanks for quick response  @mikaelim-id

**Comment by jpolstre** [comment]
> I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> 
> ` social_share: git: https://github.com/mikaelim-id/social_share`

and should not be imported into a null safe library.

**Comment by MDSADABWASIM** [comment]
> > I have done the android embedding migration. You can use this in your pubscpec.yaml temporary until my pull request merged to master.
> > ` social_share: git: https://github.com/mikaelim-id/social_share`
> 
> and should not be imported into a null safe library.

It's not null safe.

**Comment by ken-ng-esotec** [comment]
@MDSADABWASIM  i made a null safe version https://github.com/ken-ng-esotec/social_share

Just add:
```
  social_share:
    git: https://github.com/ken-ng-esotec/social_share
```

**Comment by MDSADABWASIM** [comment]
Thanks, @ken-ng-esotec for the null safe plugin

It worked with 
`ext.kotlin_version = '1.4.32'`

and 
`classpath 'com.android.tools.build:gradle:4.2.1'`
as well.

**Comment by ilyoungkim** [comment]
> 
> 
> @MDSADABWASIM i made a null safe version https://github.com/ken-ng-esotec/social_share
> 
> Just add:
> 
> ```
>   social_share:
>     git: https://github.com/ken-ng-esotec/social_share
> ```
> 
> To make it work I think consumers of the library also need to update their own project build.gradle like so:
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.5.30' <=== this
>     repositories {
>         google()
>         mavenCentral()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.2.2' <=== this
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.5'
>     }
> }
> ```
> 
> @mikaelim-id would you like to update your PR to match my one?

Thanks. good working without a deprecated version of the Android embedding message.

**Comment by jonatascm** [comment]
Any news about this?

**Comment by ShekarMudaliyar** [comment]
Apologies for the wait. Thanks to @mikaelim-id for the fix.
